server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**   # any other url also can be given after comma saperated like ,/staff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
  config:
    import: optional:configserver:http://localhost:8085


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#   service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true