server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/234199mohan/micro-configuration-service
          clone-on-start: true

