server:
  port: 8083
spring:
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: RATING-SERVICE

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#   service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
